# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-11-25 14:34
from __future__ import unicode_literals

from django.db import migrations, models
from index.change import switch


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0002_auto_20191125_1407'),
    ]

    operations = [
        migrations.AlterField(
            models_name = 'student',
            name = 'school',
            migrations.RunPython(switch),

        ),
    ]
